engines:
  rubocop:
    enabled: false
  golint:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
ratings:
  paths:
  - lib/**
  - "**.rb"
exclude_paths:
